.drone.yml
package-lock.json
package.json

Set up greenkeeper-lockfile to update files on greenkeeper dependency.

chore(package): greenkeeper lockfile steps for pipeline

---

.npmignore

chore: create npm ignore to exclude a lot of unnecessary files

---

build/scraper.js

fix: sorting and omegaAttenuation for riven 'disposition'

---

build/wikia/scrapers/WarframeScraper.js
build/wikia/scrapers/WeaponScraper.js
build/wikia/transformers/transformWarframe.js
build/wikia/transformers/transformWeapon.js
data/json/Archwing.json
data/json/Melee.json
data/json/Primary.json
data/json/Secondary.json
data/json/Warframes.json
package-lock.json

Move `wikia` urls to the updated `fandom` domain.

Wikia rename

---

build/scraper.js

Fixes image names being mismatched (for the most part) between component and non-component variants. Since we are usually prioritizing the component-named versions, those are what are being used in case of an overlap.
closes #63 
closes #52

Check Items against Existing Components

---

index.d.ts
package.json

Built this file for use in my own app and after seeing #58 not resulting in an official file I figured I'd push this back up. From within a Typescript app, the library can be used like so:
```
import Items from 'warframe-items';
const items = new Items({ category: ['All'] });
```
or if you need other types
```
import Items, { ItemsOptions } from 'warframe-items';
const options: ItemsOptions = { category: ['All'] };
const items = new Items(options);
```
I tested the validity of this by installing [typescript-json-schema](https://github.com/YousefED/typescript-json-schema) and [ajv](https://github.com/epoberezkin/ajv) and running
```
typescript-json-schema ./index.d.ts Items --out items.schema.json --noExtraProps --required --strictNullChecks
```
to generate a json-schema and then
```
ajv …
```

Added Typescript type declaration file

---

config/overrides.json

overrides for exilus mods

---

build/parser.js
config/bpConflicts.json

fix: introduce a system to filter duplicate conflicting blueprints

---

build/wikia/transformers/transformWeapon.js

Fixes for shotgun pellet counts not getting picked up when there's no pellet name

fix: area attacks & fix pellet counts

---

build/parser.js
config/itemTypes.json

fix: Augments

---

build/parser.js

fix: overrides not applying properly

---

build/build.js

it hasn't since 25.2.4, most likely due to the await, uncertain if that's the full cause

fix: readme version updating on builds

---

build/parser.js
config/overrides.json

resolves #97
1. Adding overrides for components and applying to the Kubrow Collar components

apply overrides for components

---

build/parser.js

Fixed lint errors and removed data/json from the commit
closes #110
resolves #105

sorting without data json committed

---

build/parser.js

fix majority of Issue \#5 problems
closes #5 
---
1. Fetched all items from API
2. Filter to get tradable items
3. Noticed that some were untradable but shouldn't be untradable, and same for tradable
---
You can see my fix [on this line](#line-number-467) for where the new data exists
- Is is a bug fix, feature request, or enhancement? **[Bug Fix + Enhancement]**

fix(parser): Fixed "Tradable" property conditions

---

index.d.ts

Added missing types.
---
- Does this contain a new dependency?  No
- Does this introduce opinionated data formatting or manual data entry? No
- Does this pr include the updated data files in a separate commit that can be reverted for a clean code-only pr? No
- Have I run the linter through `npm run lint`? Yes
- Is is a bug fix, feature request, or enhancement? Enhancement

Added missing types to Items

---

docker/Dockerfile
docker/Dockerfile.armhf

Added shallow clone to reduce clone efforts/speed up clone
Based on:
https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
- Does this pr include the updated data files in a separate commit that can be reverted for a clean code-only pr? **No**
- Have I run the linter through `npm run lint`? **Yes**
- Is is a bug fix, feature request, or enhancement? **Enhancement**

Shallow clone

---

index.d.ts

Fixed conflicting "introduced" item interface type.

Fix(types): Duplicate identifier "introduced"

---

.github/workflows/build.yaml
build/parser.js
build/wikia/transformers/transformWeapon.js
config/itemTypes.json
index.d.ts

I overhauled the attack structure
closes #214 
---
Lots of potential attacks were missing from wikia data
---
- Does this contain a new dependency? **[Yes]**
- Does this introduce opinionated data formatting or manual data entry? **[Yes]**, opinionated data formatting

feat: overhaul attacks [wip]

---

.github/workflows/build.yaml
.github/workflows/release.yaml
data/cache/.export.json
index.d.ts

fix patchlogs getting generated as empty

chore(ci): empty patchlogs hash to force patchlogs checking

---

package.json

Pinned Colors.js to version 1.4.0 until upstream issues are fixed
---
Start script and welcome to liberty tower. 
---
If you know you know
`https://github.com/Marak/colors.js/issues/285`

Pinned Colors.js to 1.4.0

---

build/parser.js
build/scraper.js
build/tradable.js
build/wikia/WikiaDataScraper.js
build/wikia/scrapers/WeaponScraper.js
build/wikia/transformers/transformMod.js
build/wikia/transformers/transformWarframe.js
build/wikia/transformers/transformWeapon.js
config/itemTypes.json
config/overrides.json
index.d.ts
package.json

closes #307
closes #311
closes #313 
---
1. Support parsing multiple urls for individual categories
2. de-nest 1-deep objects
3. Map infinite values to undefined
4. Replace axios in wikia parsing with node-fetch (we already had node-fetch in use, this just makes usage consistent)
5. Update types for tradability. make damaged necramech bits tradable and built primes untradable
6. Stop using wikia for types
---
there's lots
- Is is a bug fix, feature request, or enhancement? **[Bug …

fix: wikia data parsing

---

index.d.ts

closes #356 
---
1. Fix types to reflect actual options
---
You can see my fix on line 9 in index.d.ts
- Have I run the linter through `npm run lint`? **[No]**

fix(types): correctly flex category

---

.github/workflows/build.yaml
.github/workflows/regression.sh
.github/workflows/regression.yaml
.github/workflows/static.yaml
index.mjs
package.json
test/.eslintrc.yaml
test/index.regression.spec.mjs
test/index.spec.mjs

don't push the build if some data verification fail
---
1. rebuild
2. Run test
3. revert if tests fail
---
You can see my fix [on this line](#line-number-1235234) for where the new data exists
- Have I run the linter through `npm run lint`? **[No]**

ci(build): reset commit on failed post-build test

---

.github/workflows/static.yaml
.gitignore
build/build.js
build/parser.js
build/scraper.js
build/wikia/transformers/transformMod.js
build/wikia/transformers/transformWarframe.js
config/itemTypes.json
config/overrides.json
index.d.ts
package-lock.json
package.json

closes #365 
closes #368 
---
1. All the types
2. Split by category/type/etc
3. ...?
4. Profit
---
You can see my fixes mostly in index.d.ts
- Does this contain a new dependency? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Feature]**

feat: relic data, wfm names, type hardening

---

build/parser.js
index.d.ts

closes #315 
---
1. enable the `addDamage` function invocation
2. Add some types
---

feat: update parsed damage instead of raw information

---

README.md
build/build.js
build/dataHash.js
build/hashManager.js

closed \#381
---
---
- Is is a bug fix, feature request, or enhancement? **[Feature]**

feat(build): hash checking DE data before build

---

build/parser.js

n/a
---
1. remove excess console log
---
Just removes a console log

chore: clean up console log from build process

---

.github/workflows/build.yaml
.github/workflows/static.yaml

Not building, when build script changes, because of non schedule builds not being forced
---
1. Force build when it's not triggered by schedule
2. Increase build schedule frequency, _because now there shouldn't be a problem with it_
---
- Does this pr include the updated data files in a separate commit that can be reverted for a clean code-only pr? **[no]**
_It should work_

fix: force build where is needed

---

.github/workflows/build.yaml
.github/workflows/release.yaml

Up build interval, because it's getting a release more often than it should. And update the release action version, to try and fix long releases.
---

chore: up build interval

---

.github/workflows/build.yaml
.github/workflows/regression.yaml
.github/workflows/release.yaml
.github/workflows/static.yaml
package.json
test/index.spec.mjs

fixing issues on regression tests
---
1. remove extra setups
---
N/A

ci: clean up regression errors

---

.github/workflows/build.yaml
build/build.mjs
build/hashManager.mjs
build/parser.mjs
build/readJson.mjs
build/scraper.mjs

image cache not updating, making builds take a long time
---
1. Make image cache update through cache manager
2. handle saves through a single method
---
N/A

fix: handle image manifest in hash manager

---

README.md
config/variants.json

N/A
---
---
- Have I run the linter? **[No]**

fix: add sigil as a possible item name suffix

---

.github/workflows/static.yaml
config/itemTypes.json
config/overrides.json
index.d.ts
package.json
test/index.spec.mjs
test/lookup.mjs

closes #427 
---
add overrides for affected resources
---

fix: force resources to be Resource-type

---

build/build.mjs
build/parser.mjs
index.d.ts

Fixes images for abilities not being fetched, also introduces `uniqueName` key to abilities.
Since I'm not super familiar with JS I'm not entirely sure if this approach was the best way to handle it so pointers are welcomed.
---
---

fix(images): fetch icon images for abilities

---

.github/workflows/static.yaml
.nvmrc
build/proxyAgent.mjs
build/scraper.mjs
build/wikia/WikiaDataScraper.mjs
package-lock.json
test/index.regression.spec.mjs

fix some weird linting that cropped up
---
---

ci: lint, cheerio

---

build/parser.mjs
build/scraper.mjs
index.d.ts

- error for proxy failure
- typing for empty relic
---
---

fix(types): empty relic typing

---

build/parser.mjs

This fixes `vault` missing for some prime warframes. i.e. Nidus Prime was missing `vault` due to data not being available on ogg. Vault status is now retrieved from the wikia and fallsback to ogg.
---
---
- Does this contain a new dependency? **Yes**
- Does this introduce opinionated data formatting or manual data entry? **No?**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **No**

fix: missing vault status for some primes

---

config/itemTypes.json

update HeavyWeapons
---
---
- Have I run the linter? **[No]**

fix: update HeavyWeapons type

---

.github/dependabot.yml
build/build.mjs
build/network.mjs
build/scraper.mjs
build/wikia/WikiaDataScraper.mjs
test/index.regression.spec.mjs
test/index.spec.mjs

Uses dependabot to keep github actions updated
---
- Does this contain a new dependency? **[Yes]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
- Have I run the linter? **[Yes/No]**

ci: use dependabot for github actions

---

.github/dependabot.yml

closes #12312312
---
---
- Does this contain a new dependency? **[Yes/No]**
- Does this introduce opinionated data formatting or manual data entry? **[Yes/No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes/No]**
- Have I run the linter? **[Yes/No]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix/Feature/Enhancement/Docs/Maintenance]**

ci: dependency update schedule

---

.github/workflows/build.yaml
.github/workflows/regression.yaml
.github/workflows/release.yaml
.github/workflows/static.yaml
package.json

fix weird build errors
---
---
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**

ci: try to fix weird peer failures

---

index.d.ts
package-lock.json
package.json
utilities/index.d.ts

should fix some typing mismatches
---
---

fix(types): warframe-items/utilities

---

.github/workflows/release.yaml
.github/workflows/static.yaml

ci: commitlint separate job
