build/parser.js
data/json/Melee.json
data/json/Primary.json
data/json/Secondary.json

MK1-weapons have their name transformed to 'Mk1-', and wikia-url created from that name won't match in parser.addAdditionalWikiaData()

Fix MK1-weapons not matching wikia url

---

build/parser.js
build/wikia/transformers/transformWeapon.js
index.d.ts

This is required to properly compute damage over time of continuous beam
weapons (E.g. the Phage), and charge-trigger energy weapons (e.g.
Opticor).
closes WFCD/warframe-items#126

Bugfix: Add in missing chargeTime

---

build/parser.js
index.d.ts

areaAttack information missing from various weapons.  This is relevant
to all weapons with a radial damage value such as the Kulstar, Angstrum,
etc.
When looking into this information it was noticed that the damagePerShot
array includes the damage information for the radial Damage, but does
not include relevant information to help distinguish radial damage from
primary damage.  This is relevant as weapons with Radial Damage have
double-gains from all damage mods (adding Corrosion is applied to the
Primary damage and again via Radial Damage). In effect, if a weapon
supports radial damage, then the damagePerShot array is unusable for
calculating DPS of the weapon.

Bugfix: Add missing areaAttack

---

index.js

added a 'versions' field to expose the exports hashes
- Does this pr include the updated data files in a separate commit that can be reverted for a clean code-only pr? **No**
- Have I run the linter through `npm run lint`? **Yes**
- Is is a bug fix, feature request, or enhancement? **Feature**

fix: expose caches via the versions field

---

docker/Dockerfile
docker/Dockerfile.armhf

Wikia parsing requires `lua` installed. Currently it fails with since docker image doesn't have it listed in `apk install`.
---
1. `docker build`
2. `docker run`
3. `npm run build`
---
-
- Does this contain a new dependency? **Yes**
- Does this pr include the updated data files in a separate commit that can be reverted for a clean code-only pr? **No**
- Have I run the linter through `npm run lint`? **No**

Add lua to docker dependencies

---

index.d.ts

Fixed the missing ProductCategory type
---
1. Try to run the file with typescript.
---
[ProductCategory missing](#line-number-196)

Added ProductCategory type

---

.github/workflows/build.yaml
.github/workflows/ci.yaml
.github/workflows/static.yaml
build/parser.js
config/variants.json
test/index.js

closes #161 
---
1. Run tests
2. Verify all of them pass
---
You can see my additions [on this line](#diff-9a34d0e9ba5792f444e19c97f5890f8f95f624d306f216e54d7373a721156e40R575) for filtering drops

Better Drop names regex

---

index.d.ts

Fixes issue #171, where no typescript typings were provided for Item.AreaAttack.falloff
closed \#171
---
Open visual studio code
Create a index.ts file
paste in the following:
```ts
import Items from 'warframe-items'
const items = new Items({ category: ['Primary'] })
let this_line_will_error = items[0].areaAttack.falloff
```
---
This adds typings to the index.d.ts file, to describe the attribute Item.AreaAttack.falloff
- Does this introduce opinionated data formatting or manual data entry? **No, don't think so**
- Does this pr include the updated data files in a separate commit that can be reverted for a clean code-only pr? **Not sure**
- Have I run the linter through `npm run lint`? **No**
- Is is a bug fix, feature request, or enhancement? …

Adds falloff typings to index.d.ts

---

.github/workflows/build.yaml
.github/workflows/static.yaml
.gitignore

stuff not automatically building
last thing i need to take a look at is passing the bot's GH_TOKEN from the secrets so it doesn't use some random one
---
1. Let the PR build
2. Merge PR
3. Let merge commit build
4. Wait until 5 minutes before the top of the hour
5. ???
6. Success!
---
You can see my changes in .gitignore and .github/workflows/build.yaml

chore(ci): automated builds, add build into static analysis

---

build/wikia/transformers/transformWarframe.js

fix wikiaUrl being something that would redirect right off
---
N/A
---
- Is it a bug fix, feature request, or enhancement? **[Enhancement]**

fix(wikia): update prime urls to use non-redirect url

---

.eslintrc.yml
.github/dependabot.yml
build/build.js
build/dedupe.js
build/objectsort.js
build/parser.js
build/stringify.js
build/wikia/WikiaDataScraper.js
build/wikia/transformers/transformWeapon.js
package-lock.json
package.json

closes #186 
closes #188
- check better if the item is wrapped by accepted prefixes/suffixes and exclude those
- check if it's "lightly wrapped" by anything else
- move eslint config into package.json
- new objectsort (will enable if first build goes well)
- use correct dedupe
- dependabot.yml
---
1. Build it (`npm run build`)
2. check if items have about the right drops.
// they won't always be perfect, but closer is better than the bloat that is in right now
- Is is a bug fix, …

fix: non-prime dupe drops & weird image urls

---

config/itemTypes.json

Just a small change to the itemTypes.json to consider the new Tenet Hounds, so they are available in the pets.json.
---

Added new Tenet Hounds to the itemtypes

---

build/parser.js
config/itemTypes.json

Added Arch-Melee Mod and NecraMech Mod to tradableTypes.
---

Fix Arch-Melee and NecraMech mods incorrectly being flaged as not tradable.

---

build/parser.js
config/variants.json

closes #281 
---
1. Added mod sets as variants
---
Added mod sets as variants

fix: exclude set mods from prefix checks

---

.github/workflows/codeql-analysis.yml
.github/workflows/static.yaml
.npmignore
build/build.js
build/stringify.js
index.js
package.json
test/index.js

start changes for #276 
---
1. remove All.json from package (saves ~33MB)
2. Generate array of all categories on init (minus `All` and `i18n`)
2. Remove `['All']` as the default for category and replace with an array of all categories
3. Dedupe category array so we don't dupe items in "this"
4. Minify all but All.json
5. Persist build data across ci jobs
---
You can see my changes in `index.js` and test in `test/index.js`
- Is is a bug fix, feature request, or enhancement? …

perf: trim package size

---

index.js
test/index.js

Add test for what seems to be a failing call in warframe-status
---
---
- Have I run the linter through `npm run lint`? **[No]**

fix: check for raw i18n data before iterating

---

build/build.js
build/parser.js
build/wikia/WikiaDataScraper.js
build/wikia/transformers/transformWarframe.js
build/wikia/transformers/transformWeapon.js
index.d.ts

parse blueprints for market costs
---
1. add blueprints fetch before starting services
TODO:
---
see transformers
- Have I run the linter through `npm run lint`? **[No]**

feat: add market costs

---

build/parser.js
index.d.ts

Added an `isPrime` flag to make it easier to see which items are primed items.
---
You can see my addition [on this line](#line-number-763)

feat: add `isPrime` flag

---

build/parser.js

This PR fixes the capitalization of requiem relics.
Before: `Requiem Ii Exceptional`
After: `Requiem II Exceptional`
From my testing this PR shouldn't break anything else, but it might be a breaking change for some people.
---
1. Moved capitalization for names into a seperate if-statement
2. If-statement checks if the name includes both "requiem" and "relic" and if it doesn't it applies title case 
---
All changes are in build/parser.js (Line 345 and 351-355)
- Is is a bug fix, …

fix: update capitalization for requiem relics

---

build/scraper.js

1. Fixed an issue where the "Fetching API endpoints..." step would get stuck in some computers. It now has reduced concurrency but runs at roughly the same speed.
2. Fixed an issue where all language entries in the i18n were in English.
---
For issue 1, it randomly happens, especially on Windows
For issue 2, the i18n.json file after #374 has all translations in English
---
In build/scraper.js
- Does this pr include the updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]** (Data files not included)
- Is this a bug fix, feature request, or enhancement? **[Bug Fix]**

fix(i18n): inconsistency fetching i18n

---

.github/workflows/build.yaml
build/scraper.js
config/itemTypes.json
index.d.ts

closes #178
---
1. Check for the category, push more data from the scraped json
2. Run builds (which should trigger releases) on changes from build files
---
the only weird thing is mods sets are typed as "Mod Set Mods", not that i like it... but i couldn't find a better way yet

feat: parse mod sets, avionics, focus upgrades

---

config/overrides.json

Set the `Proof Fragment` item tradable property to true, as i t should be
---
1. Add an override in `overrides.json` to set the tradable property to true
---

fix(tradable): proof fragment tradable property

---

build/parser.mjs

Melee weapon category weren't present under `detectPrime` filter
---
1. Run build
2. `Ankros Prime` should have `isPrime` but doesn't
---
- Does this pr include the updated data files in a separate commit that can be reverted for a clean code-only pr? **No**
- Have I run the linter through `npm run lint`? **Yes**

fix: prime melee weapons not being detected as prime

---

build/parser.mjs
index.d.ts
test/index.spec.mjs

Looks like the wikia doesn't have an in-game market price for all items so instead of an empty string it should be set to undefined.
---
1.  Run build
2. Check Twin Krohkur
3. `marketCost: ""`
---
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **No**

fix: set `marketCost` to undefined when string is empty

---

index.d.ts

Type validation was failing on Xaku (warframe) due to missing (new) Sex typing
---
`npm run typings` returns code 1 (fail)
---
```typescript
type Sex = 'Male' | 'Female' | 'Androgynous' | 'Non-binary (Pluriform)';
```
- Is it a bug fix, feature request, or enhancement? **[Bug Fix]**

fix: add new Sex type for Xaku

---

package.json

Fixed types not being exported properly through package.json for ESM projects
---
Install warframe-items as a dependency on an ESM Typescript project (Webstorm)
---

fix(types): explicit export path in package.json

---

build/scraper.mjs
build/wikia/scrapers/ArchwingScraper.mjs
build/wikia/scrapers/CompanionScraper.mjs
build/wikia/transformers/transformCompanion.mjs
build/wikia/transformers/transformerArchwing.mjs

Doesn't fix anything just lets scarper pull information about archwings and companions. Not sure how to do everything in js so I only used the bare minimum for companions. As Archwings share a lot of information from warframes I used the same transformer.
- Does this contain a new dependency? **Yes**
- Is is a bug fix, feature request, or enhancement? **Feature**

feat: scrape archwings and companions from wikia

---

config/itemTypes.json

Fixed a case where the Archwing item type was being assigned to the Archwing quest
---
---
- Have I run the linter? **No**

fix: archwing quest getting marked as an Archwing

---

config/itemTypes.json

Fixes Ack & brunt having being marked as a melee instead of an Incarnon adapter
---
---
- Have I run the linter? **No**

fix: check for IncarnonAdapter before Melee or Rifles

---

config/itemTypes.json

Fixes Dual Swords Stavika Skin being given the the type melee
---
---
- Have I run the linter? **No**

fix: add Skins ItemType regex for melee items that are just skins

---

.github/workflows/release.yaml
.github/workflows/static.yaml
.husky/commit-msg
.husky/pre-commit
package-lock.json
package.json

commitlint, husky, lint-staged
move postinstall -> prepare, less downstream side effects
---
---
- Does this contain a new dependency? **[Yes]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**

fix: postinstall -> prepare

---

config/polarities.json
test/utilities/find.spec.mjs

Looks like DE made Dreamer's Bond a universal aura which shows up as AP_ANY when parsed in warframe-items.
https://forums.warframe.com/topic/1391568-pc-dante-unbound-deep-archimedea-hotfix-3553/?ct=1712923112
> Changed the Polarity of the Dreamer’s Bond Aura Mod from Madurai to Universal, as promised in the Whispers in the Walls: 35.1 Update where it was introduced!  
Quick note `lint-staged` seems to be running on all json files during pre-commit
---
---
https://github.com/WFCD/warframe-items/blob/e9eaa0e1500903267a356cf604c01fc4ea7cf434/data/warnings.json#L24
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only …

fix: add universal Aura polarity

---

config/overrides.json

Corufell has a `uniqueName` of `/Lotus/Weapons/Tenno/Archwing/Melee/ExaltedArchScythe/ExaltedAWScytheWeapon` and as such, is parsed as an `Arch-Melee` when it is actually a `Melee`.
This PR adds an override specifically for this weapon to have the correct `category` and `type`.
---
---

fix: corufell incorrect weapon type

---

build/build.mjs
build/parser.mjs

There are 15 generic Arcane entries that use the same base image with different names. This just does the same as blueprints where a single image exist for them.
The static image already exist inside `data/img`
---
---
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **No**
- Is is a bug fix, feature request, or enhancement? **Enhancement**

perf: skip downloading images for generic Arcanes

---

build/parser.mjs

Closes #636 
Looks like older prime secondary weapons (maybe primary too didn't check) used the full parent name i.e. `aklex-prime-lex-prime` so check if the string ends with prime and remove it.
---
---
Search for `prime-lex-prime`
https://raw.githubusercontent.com/WFCD/warframe-items/0b3f4f3c58b19ec8735676fdcdc9c9ccb1f95161/data/json/Secondary.json

fix: remove the extra `prime` in older secondary weapons
